import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './bootstrap.scss';
import './global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'NextJS 14 Bootstrap 5 Starter',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className} data-bs-theme="dark">
                {children}
            </body>
        </html>
    );
}
